### ISSUE TITLE
External resources

### ISSUE THREAD

**Issue by cjessett** [andrewfunk/prj-rev-bwfs-dasmoto#1]
(Important) Instead of [referencing external resources](https://github.com/andrewfunk/prj-rev-bwfs-dasmoto/blob/11a3a58e5e7b94b37c980f60f2ead0f531e08a74/DasmotoArts/index.html#L16) download the images then include and reference them locally. We only want to reference local resources because external url's could change or they could break, rendering a different image or none at all.

**Comment by andrewfunk** [comment]
That's a good tip. Thanks!
